# Generated by Django 5.1.3 on 2024-11-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='concertos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='carro',
            name='lavagens',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
